CREATE TABLE articles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  text TEXT NOT NULL
);

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nickname VARCHAR(80) NOT NULL,
  email VARCHAR(120) NOT NULL
);
